name: Bot de Hockey FMP

on:
  schedule:
    - cron: '*/15 * * * *' # Se ejecuta cada 15 minutos automáticamente
  workflow_dispatch: # Nos permite ejecutarlo manualmente con un botón

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar archivos
        uses: actions/checkout@v3

      - name: Preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar herramientas
        run: pip install -r requirements.txt

      - name: Ejecutar el Robot
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python scraper.py
