name: Bot Calendario FMP

on:
  schedule:
    - cron: '0 3 * * *' # Se ejecuta todos los días a las 3:00 de la madrugada
  workflow_dispatch:

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} # Usamos tu llave maestra aquí para poder escribir en tu repo

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - run: pip install -r requirements.txt
      
      - name: Ejecutar el Organizador
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python scraper.py

      - name: Ejecutar la Clasificación
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python scraper_clasificacion.py

      - name: Guardar nuevo horario del Vigilante
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Robot Organizador"
          git config --global user.email "bot@hockeypatines.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add .github/workflows/vigilante.yml
          git diff --quiet && git diff --staged --quiet || (git commit -m "⏰ Despertador dinámico actualizado para hoy" && git push)
