name: Bot Plantillas FMP

on:
  schedule:
    # A las 03:00 AM todos los días (Hora UTC) - MODO LIGERO
    - cron: '0 3 * * *'
    # A las 04:00 AM solo el día 1 de cada mes (Hora UTC) - MODO COMPLETO
    - cron: '0 4 1 * *'
  
  workflow_dispatch:
    inputs:
      tipo:
        description: 'Elige el modo de extracción:'
        required: true
        default: 'LIGERA'
        type: choice
        options:
          - LIGERA
          - COMPLETA

jobs:
  actualizar-plantillas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar librerías
        run: pip install -r requirements.txt
        
      - name: Ejecutar Extractor de Plantillas
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          # Lógica inteligente para decidir el modo
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            export TIPO_ACTUALIZACION="${{ github.event.inputs.tipo }}"
          elif [ "${{ github.event.schedule }}" == "0 4 1 * *" ]; then
            export TIPO_ACTUALIZACION="COMPLETA"
          else
            export TIPO_ACTUALIZACION="LIGERA"
          fi
          
          python scraper_plantillas.py
